[package]
name = "rust-server-error"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
derive_more = { version = "2.0",  features = ["display", "error", "from"] }
httparse = "1.10"
http = "1.3"
